version: "2"
services:

  homer:
    container_name: homer
    image: b4bz/homer:latest
    hostname: homer
    restart: always
    volumes:
      - ./config.yml:/www/config.yml
      - ./assets/:/www/assets
    environment:
      - UID=1000
      - GID=1001
    labels:
      - "traefik.http.routers.homer.rule=Host(`$DOMAIN`)"
      - "traefik.enable=true"
      - "traefik.http.routers.homer.tls=true"
      - "traefik.http.routers.homer.tls.tls.$DOMAINs[0].main=$DOMAIN"
      - "traefik.http.routers.homer.tls.tls.$DOMAINs[0].sans=-*.$DOMAIN"

networks:
  default:
    external: true
    name: $NETWORK

